export type ScreenId =
  | 'entry'
  | 'voiceEntry'
  | 'transcriptReview'
  | 'visitType'
  | 'occasion'
  | 'menu'
  | 'sensoryChips'
  | 'experienceChoice'
  | 'disappointment'
  | 'returnChoice'
  | 'comparison'
  | 'bonus'
  | 'basketball'
  | 'generating'
  | 'review';
